name: Build and Deploy
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 * * * *'
 
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
 
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
 
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: main
 
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.125.7'
 
    - name: Build
      run: hugo --minify

    - name: Make hidden dir and copy
      run: mkdir public/.well-known & cp content/.well-known/* public/.well-known
 
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "public/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "~/chs.us/"
